### ISSUE TITLE
Missing conv_4d_new.py

### ISSUE THREAD

**Issue by King-king424** [bupt-ai-cz/RestNet#3]
https://github.com/bupt-ai-cz/RestNet/blob/a66e9f39592c1ba9417d00877839d320878561b7/model/learner.py#L4C6-L4C6

**Comment by King-king424** [comment]
https://github.com/bupt-ai-cz/RestNet/blob/a66e9f39592c1ba9417d00877839d320878561b7/model/base/correlation.py#L13C15-L13C15
There seems to be a problem here too

**Comment by xinyanghuang7** [comment]
I will fix it soon.
