### ISSUE TITLE
About inference

### ISSUE THREAD

**Issue by King-king424** [bupt-ai-cz/RestNet#4]
https://github.com/bupt-ai-cz/RestNet/blob/b1db0839d53dbe60c9b073b701ad45aa54d230e4/test.py#L27
![image](https://github.com/bupt-ai-cz/RestNet/assets/39642013/5cce21f8-0a13-4fb5-b61a-991fb07b8632)
![image](https://github.com/bupt-ai-cz/RestNet/assets/39642013/ead768f9-dff5-421b-a2e5-0f5da1cdf995)
I wonder if you also need to forward twice when testing?
It is not clear if there is an omission here

**Comment by xinyanghuang7** [comment]
When testing, we usually do not consider two propagation.
