### ISSUE TITLE
test  detail

### ISSUE THREAD

**Issue by King-king424** [bupt-ai-cz/RestNet#5]
![image](https://github.com/bupt-ai-cz/RestNet/assets/39642013/23ce5406-df3e-403c-a383-8bbe6f7de850)
![image](https://github.com/bupt-ai-cz/RestNet/assets/39642013/4cf0d1ea-0fe2-4b92-8342-532c4a908a59)
Is this setting to 600 or 1200?

**Comment by King-king424** [comment]
could not achieve the performance reported in paper
----------------------------------------------------------------------
RestNet
isic    42.25; 51.10;
lung    70.43; 73.69;
fss     81.53; 84.89;

------------------------------------------------------------------------------------------
seed from 0 to 4

once forward
lung
==================== best seed ====================
best-seed: 2 	 mIoU: 46.24 	 FB-IoU: 53.67
==================== worset seed ====================
worst-seed: 3 	 mIoU: 45.68 	 FB-IoU: 53.25
==================== average performance ====================
mIoU: 45.98 	 FB-IoU: 53.52
==================== Finished Testing ====================

isic
==================== best seed ====================
best-seed: 3 	 mIoU: 28.07 	 FB-IoU: 32.96
==================== worset seed ====================
worst-seed: 1 	 mIoU: 27.06 	 FB-IoU: 31.97
==================== average performance ====================
mIoU: 27.38 	 FB-IoU: 32.88
==================== Finished Testing ====================

fss
==================== best seed ====================
best-seed: 4 	 mIoU: 80.15 	 FB-IoU: 87.06
==================== worset seed ====================
worst-seed: 1 	 mIoU: 79.65 	 FB-IoU: 86.53
==================== average performance ====================
mIoU: 79.88 	 FB-IoU: 86.78
==================== Finished Testing ====================

deepglobe
==================== best seed ====================
best-seed: 1 	 mIoU: 23.92 	 FB-IoU: 38.51
==================== worset seed ====================
worst-seed: 4 	 mIoU: 21.27 	 FB-IoU: 37.25
==================== average performance ====================
mIoU: 22.67 	 FB-IoU: 38.09
==================== Finished Testing ====================

------------------------------------------------------------------------------------------
twice forward
lung
==================== best seed ====================
best-seed: 2     mIoU: 58.83     FB-IoU: 67.84
==================== worset seed ====================
worst-seed: 4    mIoU: 57.83     FB-IoU: 67.27
==================== average performance ====================
mIoU: 58.17      FB-IoU: 67.36
==================== Finished Testing ====================

isic
==================== best seed ====================
best-seed: 4     mIoU: 35.24     FB-IoU: 45.20
==================== worset seed ====================
worst-seed: 2    mIoU: 30.69     FB-IoU: 42.36
==================== average performance ====================
mIoU: 32.16      FB-IoU: 43.02
==================== Finished Testing ====================

deepglobe
==================== best seed ====================
best-seed: 1     mIoU: 23.36     FB-IoU: 38.91
==================== worset seed ====================
worst-seed: 4    mIoU: 22.10     FB-IoU: 38.27
==================== average performance ====================
mIoU: 22.91      FB-IoU: 38.89
==================== Finished Testing ====================

fss
==================== best seed ====================
best-seed: 4     mIoU: 82.70     FB-IoU: 89.03
==================== worset seed ====================
worst-seed: 2    mIoU: 82.31     FB-IoU: 88.71
==================== average performance ====================
mIoU: 82.49      FB-IoU: 88.81
==================== Finished Testing ====================

**Comment by xinyanghuang7** [comment]
Regarding isic, our experiment is based on PATNet, and for the convenience of comparison, our settings are the same.
Regarding the experimental results, we have provided experimental checkpoints for FSS-1000 for replication, but may require retraining for other datasets.
Meanwhile, this questioning method is too vague and has too many possibilities, including environment, configuration, data, bugs, and even machines, making it difficult to answer directly.

**Comment by King-king424** [comment]
I used the checkpoints you provided to test.
I tested on the A100 and A6000 and got similar results to what I provided.
I also train from scratch based on the code you provided. Go to the test and get similar results.

**Comment by King-king424** [comment]
This task is to complete training on VOC and test on fss, isic, etc. data. If you do not adapt during testing, there is no need to retrain for data such as FSS, ISIC, etc.
And the method you propose is not to do adaptation during testing. Therefore, it should be reasonable to test on 4 datasets based on one weight you provide.

**Comment by King-king424** [comment]
Randomness may affect some accuracy, but such a large gap is a small probability event.
I have tried your method. The residual connection can accelerate convergence, but affect cross-domain performance.
