### ISSUE TITLE
Have the backbone of ViT or other transformer based methods been tested as your backbone?

### ISSUE THREAD

**Issue by JIaqiYang78** [bupt-ai-cz/RestNet#6]
Hello author,

I found that your backbone is based on Resnet, and now it's a very popular transformer like ViT-based models. So, I want to ask if you have tried and tested on the backbone of ViT. Can you provide some open links for ViT-based models applied on Cross-domain and few-shot segmentation?

**Comment by xinyanghuang7** [comment]
Thanks for your question, great idea!

Few-shot segmentation based on cross-domain may lack exploration on ViT, but few-shot segmentation in general scenarios has been partially explored on ViT.

I can provide you with a few links:

https://proceedings.neurips.cc/paper_files/paper/2022/hash/2ae33575c3374050654ae7802326c81d-Abstract-Conference.html

https://proceedings.neurips.cc/paper/2021/hash/b8b12f949378552c21f28deff8ba8eb6-Abstract.html

https://openaccess.thecvf.com/content/ICCV2021/html/Lu_Simpler_Is_Better_Few-Shot_Semantic_Segmentation_With_Classifier_Weight_Transformer_ICCV_2021_paper.html

https://openaccess.thecvf.com/content/ICCV2021/papers/Lu_Simpler_Is_Better_Few-Shot_Semantic_Segmentation_With_Classifier_Weight_Transformer_ICCV_2021_paper.pdf

Hope this helps with your research, thanks!
